name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Debug environment variables
      run: |
        echo "Checking environment variables..."
        echo "VITE_SUPABASE_URL is set: ${{ secrets.VITE_SUPABASE_URL != '' }}"
        echo "VITE_SUPABASE_ANON_KEY is set: ${{ secrets.VITE_SUPABASE_ANON_KEY != '' }}"
        echo "VITE_SUPABASE_URL length: ${#VITE_SUPABASE_URL}"
        echo "VITE_SUPABASE_ANON_KEY length: ${#VITE_SUPABASE_ANON_KEY}"
        if [ -z "$VITE_SUPABASE_URL" ]; then
          echo "❌ VITE_SUPABASE_URL is empty or not set"
        else
          echo "✅ VITE_SUPABASE_URL is set (first 20 chars): ${VITE_SUPABASE_URL:0:20}..."
        fi
        if [ -z "$VITE_SUPABASE_ANON_KEY" ]; then
          echo "❌ VITE_SUPABASE_ANON_KEY is empty or not set"
        else
          echo "✅ VITE_SUPABASE_ANON_KEY is set (first 20 chars): ${VITE_SUPABASE_ANON_KEY:0:20}..."
        fi
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        
    - name: Build
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL || env.VITE_SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY || env.VITE_SUPABASE_ANON_KEY }}
      
    - name: Verify build output
      run: |
        echo "Build completed. Checking output..."
        ls -la dist/
        echo "Contents of index.html:"
        cat dist/index.html
        echo "Checking for main JS file:"
        ls -la dist/assets/
      
    - name: Setup Pages
      uses: actions/configure-pages@v5
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4 